### ISSUE TITLE
Poor Performance on Graphene OS A14

### ISSUE THREAD

**Issue by meowmeowofthemeows** [topminipie/OpenCord#66]
Hi there dev, I was so glad to see someone has picked up this project if only a little, and I decided to try it out. Upon using the app it is incredible slow and laggy. The animations are choppy and all and I really want to use this app but as of now it is unuseable.

**Comment by ThatOneCalculator** [comment]
I can also reproduce this on Graphene, however, I think the vast majority of the lag actually comes from it being a debug build rather than a release build (as graphene's hardener really doesn't like how Android debugging works)

**Comment by ThatOneCalculator** [comment]
Most of the lag is gone! It's not super smooth but ***way*** better than before, thank you :)

**Comment by ThatOneCalculator** [comment]
After testing for a bit, I think this can safely be closed.

**Comment by meowmeowofthemeows** [comment]
Thanks for coming here and solving it, I also suspected it was because of the debug build but I was unable to compile a proper release. Long Live Opencord!
